sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - wget https://www.stackage.org/stack/linux-x86_64 -O stack.tar.gz
  - tar xf stack.tar.gz
  - mkdir -p $HOME/.local/bin
  - cp stack-*-linux-x86_64/stack $HOME/.local/bin/stack
  - stack setup
  - stack install hlint

install:
  - stack build

script:
  - hlint src
  - stack test

cache:
  directories:
    - $HOME/.stack
    - .stack-work/install

before_deploy:
  - cp $(stack path --local-install-root)/bin/uv-alert-server .

deploy:
  provider: releases
  api_key:
    secure: J2UkDgs+WwtLRxm94seqP/8LSKs+/uPF9K4MNzqasHPY3KmMKpmVhxl8gSwMFuTMp7H5+ERWuX3S0g2ftw2d3BVhV+7nLjzJV1YNaI8f1Dj7PTPNGRGjOthCpt2ZsMQq4IQ3eeAX62Is/QD9tBRrLqAf1dcF68psy7kepK7h987yfoKMoxNxPxLBu30WZ5Ub7WCcsnlYYYzPnLaF/ERtWtMP8Zhp1Ut1xsIc//WEPed+e6Ap4knNUrHyPYK1AqSAM7tVf5nxhUhq98REkU8MoKI9yg4SBbWNQtCxL75UtBzerOC2f5stZTk87IU0OBC/Ut1Eqd9Yo/KcGpoHd6oLDvIoQ5WFKjacpvpFgB7Pj5QL3g5hfgpavyqbCIxm329NmBcH1fCYhwseYoK5V78wHyF5IP15EaOkdECU+v5iOo1ElOFkLDunhWmFdW5VcRy1ONG9k7uBPne7N6C7QcBLNU9DNV6unBi996BOnmY7qr/Gv/FXTb17qkjRPab9Z7x24dof0ri0EJHhq5fOs4vIVwEve5+WK9njMcZw7wrdF+Iq749VZ/tBH7jRdV4fSxgckmBGHbets78vh1h6PviQAObCz3xvwVavD7f4h+5FuqLM+Sdu5i4dEXfXkBbymbPhYa3ibkNXiVq2kymLRh45cWqGLFjuN0YT6f52AJY46ZI=
  file: uv-alert-server
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: koterpillar/uv-alert-server
