resolver: lts-6.7
packages:
- '.'
- location:
    git: https://github.com/koterpillar/hspec-wai.git
    commit: f1a8469436bad842762034e2feabee387e9fb4de
  subdirs:
    - .
    - hspec-wai-json
  extra-dep: true
extra-deps:
  - ftphs-1.0.9.1
  - timezone-olson-th-0.1.0.1
flags: {}
