module Fetcher.EPA.Cities (
    usLocations,
    usStateAbbreviation,
) where

import qualified Data.Map as M

import Types.Location


usCities :: [(String, String)]
usCities = [ ("New York", "New York")
           , ("Los Angeles", "California")
           , ("Chicago", "Illinois")
           , ("Houston", "Texas")
           , ("Philadelphia", "Pennsylvania")
           , ("Phoenix", "Arizona")
           , ("San Antonio", "Texas")
           , ("San Diego", "California")
           , ("Dallas", "Texas")
           , ("San Jose", "California")
           , ("Austin", "Texas")
           , ("Jacksonville", "Florida")
           , ("San Francisco", "California")
           , ("Indianapolis", "Indiana")
           , ("Columbus", "Ohio")
           , ("Fort Worth", "Texas")
           , ("Charlotte", "North Carolina")
           , ("Detroit", "Michigan")
           , ("El Paso", "Texas")
           , ("Seattle", "Washington")
           , ("Denver", "Colorado")
           , ("Washington", "District of Columbia")
           , ("Memphis", "Tennessee")
           , ("Boston", "Massachusetts")
           , ("Nashville", "Tennessee")
           , ("Baltimore", "Maryland")
           , ("Oklahoma City", "Oklahoma")
           , ("Portland", "Oregon")
           , ("Las Vegas", "Nevada")
           , ("Louisville", "Kentucky")
           , ("Milwaukee", "Wisconsin")
           , ("Albuquerque", "New Mexico")
           , ("Tucson", "Arizona")
           , ("Fresno", "California")
           , ("Sacramento", "California")
           , ("Long Beach", "California")
           , ("Kansas City", "Missouri")
           , ("Mesa", "Arizona")
           , ("Atlanta", "Georgia")
           , ("Virginia Beach", "Virginia")
           , ("Omaha", "Nebraska")
           , ("Colorado Springs", "Colorado")
           , ("Raleigh", "North Carolina")
           , ("Miami", "Florida")
           , ("Oakland", "California")
           , ("Minneapolis", "Minnesota")
           , ("Tulsa", "Oklahoma")
           , ("Cleveland", "Ohio")
           , ("Wichita", "Kansas")
           , ("New Orleans", "Louisiana")
           , ("Arlington", "Texas")
           , ("Bakersfield", "California")
           , ("Tampa", "Florida")
           , ("Aurora", "Colorado")
           , ("Honolulu", "Hawaii")
           , ("Anaheim", "California")
           , ("Santa Ana", "California")
           , ("Corpus Christi", "Texas")
           , ("Riverside", "California")
           , ("St. Louis", "Missouri")
           , ("Lexington", "Kentucky")
           , ("Pittsburgh", "Pennsylvania")
           , ("Stockton", "California")
           , ("Anchorage", "Alaska")
           , ("Cincinnati", "Ohio")
           , ("Saint Paul", "Minnesota")
           , ("Greensboro", "North Carolina")
           , ("Toledo", "Ohio")
           , ("Newark", "New Jersey")
           , ("Plano", "Texas")
           , ("Henderson", "Nevada")
           , ("Lincoln", "Nebraska")
           , ("Orlando", "Florida")
           , ("Jersey City", "New Jersey")
           , ("Chula Vista", "California")
           , ("Buffalo", "New York")
           , ("Fort Wayne", "Indiana")
           , ("Chandler", "Arizona")
           , ("St. Petersburg", "Florida")
           , ("Laredo", "Texas")
           , ("Durham", "North Carolina")
           , ("Irvine", "California")
           , ("Madison", "Wisconsin")
           , ("Norfolk", "Virginia")
           , ("Lubbock", "Texas")
           , ("Gilbert", "Arizona")
           , ("Winston-Salem", "North Carolina")
           , ("Glendale", "Arizona")
           , ("Reno", "Nevada")
           , ("Hialeah", "Florida")
           , ("Garland", "Texas")
           , ("Chesapeake", "Virginia")
           , ("Irving", "Texas")
           , ("North Las Vegas", "Nevada")
           , ("Scottsdale", "Arizona")
           , ("Baton Rouge", "Louisiana")
           , ("Fremont", "California")
           , ("Richmond", "Virginia")
           , ("Boise", "Idaho")
           , ("San Bernardino", "California")
           , ("Birmingham", "Alabama")
           , ("Spokane", "Washington")
           , ("Rochester", "New York")
           , ("Modesto", "California")
           , ("Des Moines", "Iowa")
           , ("Oxnard", "California")
           , ("Tacoma", "Washington")
           , ("Fontana", "California")
           , ("Fayetteville", "North Carolina")
           , ("Moreno Valley", "California")
           , ("Columbus", "Georgia")
           , ("Huntington Beach", "California")
           , ("Yonkers", "New York")
           , ("Montgomery", "Alabama")
           , ("Aurora", "Illinois")
           , ("Glendale", "California")
           , ("Shreveport", "Louisiana")
           , ("Akron", "Ohio")
           , ("Little Rock", "Arkansas")
           , ("Amarillo", "Texas")
           , ("Augusta", "Georgia")
           , ("Mobile", "Alabama")
           , ("Grand Rapids", "Michigan")
           , ("Salt Lake City", "Utah")
           , ("Huntsville", "Alabama")
           , ("Tallahassee", "Florida")
           , ("Grand Prairie", "Texas")
           , ("Overland Park", "Kansas")
           , ("Knoxville", "Tennessee")
           , ("Brownsville", "Texas")
           , ("Worcester", "Massachusetts")
           , ("Newport News", "Virginia")
           , ("Santa Clarita", "California")
           , ("Providence", "Rhode Island")
           , ("Fort Lauderdale", "Florida")
           , ("Garden Grove", "California")
           , ("Oceanside", "California")
           , ("Rancho Cucamonga", "California")
           , ("Santa Rosa", "California")
           , ("Port St. Lucie", "Florida")
           , ("Chattanooga", "Tennessee")
           , ("Tempe", "Arizona")
           , ("Jackson", "Mississippi")
           , ("Cape Coral", "Florida")
           , ("Vancouver", "Washington")
           , ("Ontario", "California")
           , ("Sioux Falls", "South Dakota")
           , ("Peoria", "Arizona")
           , ("Springfield", "Missouri")
           , ("Pembroke Pines", "Florida")
           , ("Elk Grove", "California")
           , ("Salem", "Oregon")
           , ("Corona", "California")
           , ("Lancaster", "California")
           , ("Eugene", "Oregon")
           , ("Palmdale", "California")
           , ("McKinney", "Texas")
           , ("Salinas", "California")
           , ("Fort Collins", "Colorado")
           , ("Cary", "North Carolina")
           , ("Hayward", "California")
           , ("Springfield", "Massachusetts")
           , ("Pasadena", "Texas")
           , ("Macon", "Georgia")
           , ("Pomona", "California")
           , ("Alexandria", "Virginia")
           , ("Escondido", "California")
           , ("Sunnyvale", "California")
           , ("Lakewood", "Colorado")
           , ("Kansas City", "Kansas")
           , ("Rockford", "Illinois")
           , ("Torrance", "California")
           , ("Hollywood", "Florida")
           , ("Joliet", "Illinois")
           , ("Bridgeport", "Connecticut")
           , ("Clarksville", "Tennessee")
           , ("Paterson", "New Jersey")
           , ("Frisco", "Texas")
           , ("Mesquite", "Texas")
           , ("Savannah", "Georgia")
           , ("Syracuse", "New York")
           , ("Dayton", "Ohio")
           , ("Pasadena", "California")
           , ("Orange", "California")
           , ("Fullerton", "California")
           , ("McAllen", "Texas")
           , ("Killeen", "Texas")
           , ("Hampton", "Virginia")
           , ("Bellevue", "Washington")
           , ("Warren", "Michigan")
           , ("Miramar", "Florida")
           , ("West Valley City", "Utah")
           , ("Olathe", "Kansas")
           , ("Columbia", "South Carolina")
           , ("Sterling Heights", "Michigan")
           , ("Thornton", "Colorado")
           , ("New Haven", "Connecticut")
           , ("Waco", "Texas")
           , ("Charleston", "South Carolina")
           ]

usLocations :: [Location]
usLocations = map usLocation usCities
    where usLocation (city, state) = Location "USA" state city

usStateAbbreviations :: M.Map String String
usStateAbbreviations = M.fromList [ ("Alabama", "AL")
                                  , ("Alaska", "AK")
                                  , ("Arizona", "AZ")
                                  , ("Arkansas", "AR")
                                  , ("California", "CA")
                                  , ("Colorado", "CO")
                                  , ("Connecticut", "CT")
                                  , ("Delaware", "DE")
                                  , ("Florida", "FL")
                                  , ("Georgia", "GA")
                                  , ("Hawaii", "HI")
                                  , ("Idaho", "ID")
                                  , ("Illinois", "IL")
                                  , ("Indiana", "IN")
                                  , ("Iowa", "IA")
                                  , ("Kansas", "KS")
                                  , ("Kentucky", "KY")
                                  , ("Louisiana", "LA")
                                  , ("Maine", "ME")
                                  , ("Maryland", "MD")
                                  , ("Massachusetts", "MA")
                                  , ("Michigan", "MI")
                                  , ("Minnesota", "MN")
                                  , ("Mississippi", "MS")
                                  , ("Missouri", "MO")
                                  , ("Montana", "MT")
                                  , ("Nebraska", "NE")
                                  , ("Nevada", "NV")
                                  , ("New Hampshire", "NH")
                                  , ("New Jersey", "NJ")
                                  , ("New Mexico", "NM")
                                  , ("New York", "NY")
                                  , ("North Carolina", "NC")
                                  , ("North Dakota", "ND")
                                  , ("Ohio", "OH")
                                  , ("Oklahoma", "OK")
                                  , ("Oregon", "OR")
                                  , ("Pennsylvania", "PA")
                                  , ("Rhode Island", "RI")
                                  , ("South Carolina", "SC")
                                  , ("South Dakota", "SD")
                                  , ("Tennessee", "TN")
                                  , ("Texas", "TX")
                                  , ("Utah", "UT")
                                  , ("Vermont", "VT")
                                  , ("Virginia", "VA")
                                  , ("Washington", "WA")
                                  , ("West Virginia", "WV")
                                  , ("Wisconsin", "WI")
                                  , ("Wyoming", "WY")
                                  , ("American Samoa", "AS")
                                  , ("District of Columbia", "DC")
                                  , ("Federated States of Micronesia", "FM")
                                  , ("Guam", "GU")
                                  , ("Marshall Islands", "MH")
                                  , ("Northern Mariana Islands", "MP")
                                  , ("Palau", "PW")
                                  , ("Puerto Rico", "PR")
                                  , ("Virgin Islands", "VI")
                                  ]

usStateAbbreviation :: String -> String
usStateAbbreviation state = case M.lookup state usStateAbbreviations of
                              Just abbr -> abbr
                              Nothing -> error $ "Invalid state " ++ state
