{-# Language RecordWildCards #-}
{-# Language TemplateHaskell #-}
module TZ where

import Data.Time.LocalTime.TimeZone.Series
import Data.Time.LocalTime.TimeZone.Olson.TH


cityTZ :: String -> TimeZoneSeries
cityTZ city = case city of
    "Darwin" -> tzNorth
    "Melbourne" -> tzVictoria
    "Sydney" -> tzNSW
    "Hobart" -> tzTasmania
    "Perth" -> tzWest
    "Adelaide" -> tzSouth
    "Alice Springs" -> tzNorth
    "Brisbane" -> tzQueensland
    "Canberra" -> tzCanberra
    "Mildura" -> tzVictoria
    -- "Broome"
    "Townsville" -> tzQueensland
    -- "Mt Isa"
    -- "Albany"
    -- "Armidale"
    -- "Batemans Bay"
    -- "Bathurst"
    -- "Bourke"
    -- "Bowral"
    -- "Broken Hill"
    -- "Cape Byron"
    -- "Cessnock"
    -- "Cobar"
    -- "Coffs Harbour"
    -- "Cooma"
    -- "Deniliquin"
    -- "Dubbo"
    "Gosford" -> tzNSW
    -- "Goulburn"
    -- "Grafton"
    -- "Griffith"
    -- "Inverell"
    -- "Katoomba"
    -- "Kempsey"
    -- "Lismore"
    -- "Maitland NSW"
    -- "Moree"
    -- "Mudgee"
    "Newcastle" -> tzNSW
    -- "Nowra"
    -- "Orange"
    -- "Parkes"
    -- "Port Macquarie"
    -- "Scone"
    -- "Tamworth"
    -- "Taree"
    -- "Wagga Wagga"
    -- "Wollongong"
    -- "Cabramurra"
    -- "Perisher Valley"
    -- "Thredbo"
    -- "Bairnsdale"
    -- "Ballarat"
    -- "Bendigo"
    -- "Colac"
    -- "Echuca"
    -- "Geelong"
    -- "Hamilton"
    -- "Horsham"
    -- "LaTrobe Valley"
    -- "Mornington"
    -- "Orbost"
    -- "Sale"
    -- "Seymour"
    -- "Shepparton"
    -- "Swan Hill"
    -- "Wangaratta"
    -- "Warrnambool"
    -- "Albury-Wodonga"
    -- "Wonthaggi"
    -- "Yarra Glen"
    -- "Mount Buller"
    -- "Mount Hotham"
    -- "Ipswich"
    -- "Ayr-Home Hill"
    -- "Biloela"
    -- "Bowen"
    -- "Bundaberg"
    -- "Cairns"
    -- "Charleville"
    -- "Charters Towers"
    -- "Clermont"
    -- "Gold Coast"
    -- "Dalby"
    -- "Emerald"
    -- "Gladstone"
    -- "Goondiwindi"
    -- "Gympie"
    -- "Hervey Bay"
    -- "Ingham"
    -- "Innisfail"
    -- "Kingaroy"
    -- "Longreach"
    -- "Mackay"
    -- "Mareeba"
    -- "Maryborough"
    -- "Moranbah"
    -- "Rockhampton"
    -- "Roma"
    -- "Sunshine Coast"
    -- "Toowoomba"
    -- "Warwick"
    -- "Winton"
    -- "Yeppoon"
    -- "Burnie"
    -- "Devonport"
    -- "Launceston"
    -- "St Helens"
    -- "Strahan"
    -- "Swansea"
    -- "Bridgetown"
    -- "Bunbury"
    -- "Busselton"
    -- "Carnarvon"
    -- "Collie"
    -- "Dalwallinu"
    -- "Denham"
    -- "Derby"
    -- "Esperance"
    -- "Eucla"
    -- "Exmouth"
    -- "Geraldton"
    -- "Halls Creek"
    -- "Kalbarri"
    -- "Kalgoorlie"
    -- "Kalumburu"
    -- "Karratha"
    -- "Katanning"
    -- "Kununurra"
    -- "Lake Grace"
    -- "Leinster"
    -- "Mandurah"
    -- "Manjimup"
    -- "Munjina"
    -- "Marble Bar"
    -- "Margaret River"
    -- "Meekatharra"
    -- "Merredin"
    -- "Moora"
    -- "Morawa"
    -- "Narrogin"
    -- "Newman"
    -- "Northam"
    -- "Onslow"
    -- "Pannawonica"
    -- "Paraburdoo"
    -- "Port Hedland"
    -- "Ravensthorpe"
    -- "Roebourne"
    -- "Tom Price"
    -- "Alyangula"
    -- "Borroloola"
    -- "Jabiru"
    -- "Katherine"
    -- "Nhulunbuy-Gove"
    -- "Tennant Creek"
    -- "Yulara"
    -- "Albury-Wodonga"
    -- "Ceduna"
    -- "Clare"
    -- "Coober Pedy"
    -- "Coonawarra"
    -- "Keith"
    -- "Kingscote"
    -- "Leigh Creek"
    -- "Maitland SA"
    -- "Mount Gambier"
    -- "Murray Bridge"
    -- "Naracoorte"
    -- "Nuriootpa"
    -- "Port Pirie"
    -- "Port Augusta"
    -- "Port Lincoln"
    -- "Renmark"
    -- "Roxby Downs"
    -- "Victor Harbor"
    -- "Whyalla"
    -- "Woomera"
    -- "Wudinna"
    -- "Argyle"
    -- "Fitzroy Crossing"
    -- "Wyndham"
    -- "Barcaldine"
    -- "Burketown"
    -- "Cloncurry"
    -- "Cooktown"
    -- "Coolangatta"
    -- "Normanton"
    -- "Richmond"
    -- "Thursday Island"
    -- "Christmas Island"
    -- "Cocos Islands"
    -- "Lord Howe Island"
    -- "Norfolk Island"
    -- "Boulia"
    -- "Hughenden"
    -- "Weipa"
    -- "Forster"
    -- "Glen Innes"
    -- "Ivanhoe"
    -- "Lithgow"
    -- "Merimbula"
    -- "Narrabri"
    -- "Singleton"
    -- "Springwood"
    -- "Tuggeranong"
    -- "Young"
    -- "Pirlangimpi"
    -- "Maningrida"
    -- "Wadeye"
    -- "Lajamanu"
    -- "Yuendumu"
    -- "Frankston"
    -- "Laverton"
    -- "Mount Dandenong"
    -- "Scoresby"
    -- "Tullamarine"
    -- "Watsonia"
    -- "Amberley"
    -- "Tewantin"
    -- "Liawenee"
    -- "King Island"
    -- "Flinders Island"
    "Kingston" -> tzTasmania
    -- "Mt Baw Baw"
    -- "Falls Creek"
    -- "Charlotte Pass"
    -- "Selwyn Snowfields"
    -- "Smithton"
    -- "Ulverstone"
    -- "Scottsdale"
    -- "Campbell Town"
    -- "Queenstown"
    -- "New Norfolk"
    _ -> tzVictoria -- TODO

tzNSW = $(loadTZFile "/usr/share/zoneinfo/Australia/NSW")
tzNorth = $(loadTZFile "/usr/share/zoneinfo/Australia/North")
tzSouth = $(loadTZFile "/usr/share/zoneinfo/Australia/South")
tzQueensland = $(loadTZFile "/usr/share/zoneinfo/Australia/Queensland")
tzWest = $(loadTZFile "/usr/share/zoneinfo/Australia/West")
tzVictoria = $(loadTZFile "/usr/share/zoneinfo/Australia/Victoria")
tzTasmania = $(loadTZFile "/usr/share/zoneinfo/Australia/Tasmania")
tzCanberra = $(loadTZFile "/usr/share/zoneinfo/Australia/Canberra")
